project:
  type: book
  output-dir: docs
  
book:
  title: Visualization Curriculum
  author: Jeffrey Heer, Dominik Moritz, Jake VanderPlas, and Brock Craft
  logo: altair-hist.png
  repo-url: https://github.com/uwdata/visualization-curriculum
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook]
  chapters:
    - index.md
    - part: Curriculum
      chapters:
        - altair_introduction.ipynb
        - altair_marks_encoding.ipynb
        - altair_data_transformation.ipynb
        - altair_scales_axes_legends.ipynb
        - altair_view_composition.ipynb
        - altair_interaction.ipynb
        - altair_cartographic.ipynb
    - part: Support
      chapters:
        - altair_debugging.ipynb

format:
  html:
    theme: cosmo

